import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { Weight } from "lucide-react";

// const jetbrainsMono = JetBrains_Mono({
//   variable: "--font-jetbrains-mono", // Keep this consistent
//   subsets: ["latin"],
//   weight: ["100", "200", "300", "400", "500", "600", "700", "800"], // lowercase 'weight'
// });

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrainsMono",
  subsets: ["latin"],
  // weight: "variable",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jetbrainsMono.variable}>
        {children}
      </body>
    </html>
  );
}
